In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [29]:
url_csv = '/content/CustomerOrders.csv'
df = pd.read_csv(url_csv)
display(df.head(10))

,OrderID,CustomerID,OrderRegion,OrderDate,OrderAmount,ProductID,Quantity
0,101,1,Yorkshire,2023-07-01,150.0,1001.0,1.0
1,102,2,Tyne & Wear,2023-07-03,NaN,1002.0,2.0
2,103,1,Yorkshire,INVALID_DATE,200.5,1001.0,NaN
3,104,3,London,2023-07-05,350.0,NaN,4.0
4,105,2,Tyne & Wear,2023-07-03,One Hundred Pounds,1003.0,1.0
5,106,1,Yorkshire,2023-07-01,150.0,1001.0,1.0
6,107,2,Tyne & Wear,2023-07-03,One Hundred Pounds,1003.0,1.0
7,108,1,Yorkshire,INVALID_DATE,50.0,1006.0,Three
8,109,3,London,2023-07-05,970.0,NaN,3.0
9,110,2,Tyne & Wear,2023-07-23,NaN,1010.0,1.0

In [30]:
# Check missing values
df.isna()

,OrderID,CustomerID,OrderRegion,OrderDate,OrderAmount,ProductID,Quantity
0,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False
2,False,False,False,False,False,False,True
3,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,True,False
9,False,False,False,False,True,False,False

In [31]:
# Check rows where any element is missing
df[df.isna().any(axis=1)]

,OrderID,CustomerID,OrderRegion,OrderDate,OrderAmount,ProductID,Quantity
1,102,2,Tyne & Wear,2023-07-03,NaN,1002.0,2.0
2,103,1,Yorkshire,INVALID_DATE,200.5,1001.0,NaN
3,104,3,London,2023-07-05,350.0,NaN,4.0
8,109,3,London,2023-07-05,970.0,NaN,3.0
9,110,2,Tyne & Wear,2023-07-23,NaN,1010.0,1.0

In [32]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [OrderID, CustomerID, OrderRegion, OrderDate, OrderAmount, ProductID, Quantity]
Index: []

In [33]:
df['OrderDate'].dtype

dtype('O')

In [34]:
# Fix the dates and convert to a date datatype.
df['OrderDate'] = df['OrderDate'].replace("INVALID_DATE", "2023-07-01")
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

In [37]:
df.head(10)

,OrderID,CustomerID,OrderRegion,OrderDate,OrderAmount,ProductID,Quantity
0,101,1,Yorkshire,2023-07-01,150.0,1001.0,1.0
2,103,1,Yorkshire,2023-07-01,200.5,1001.0,NaN
3,104,3,London,2023-07-05,350.0,NaN,4.0
4,105,2,Tyne & Wear,2023-07-03,One Hundred Pounds,1003.0,1.0
5,106,1,Yorkshire,2023-07-01,150.0,1001.0,1.0
6,107,2,Tyne & Wear,2023-07-03,One Hundred Pounds,1003.0,1.0
7,108,1,Yorkshire,2023-07-01,50.0,1006.0,Three
8,109,3,London,2023-07-05,970.0,NaN,3.0

In [39]:
# Fix OrderAmount.
df['OrderAmount'].replace('One Hundred Pounds', 100.0, inplace=True)
df.head(10)

/tmp/ipython-input-39-1411287375.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['OrderAmount'].replace('One Hundred Pounds', 100.0, inplace=True)

   OrderID  CustomerID  OrderRegion  OrderDate OrderAmount  ProductID Quantity
0      101           1    Yorkshire 2023-07-01       150.0     1001.0      1.0
2      103           1    Yorkshire 2023-07-01       200.5     1001.0      NaN
3      104           3       London 2023-07-05       350.0        NaN      4.0
4      105           2  Tyne & Wear 2023-07-03       100.0     1003.0      1.0
5      106           1    Yorkshire 2023-07-01       150.0     1001.0      1.0
6      107           2  Tyne & Wear 2023-07-03       100.0     1003.0      1.0
7      108           1    Yorkshire 2023-07-01        50.0     1006.0    Three
8      109           3       London 2023-07-05       970.0        NaN      3.0

In [45]:
import numpy as np
# Replace missing ProductID values with the default 1000 value.
df['ProductID'] = df['ProductID'].fillna(1000)
df.head(10)

   OrderID  CustomerID  OrderRegion  OrderDate OrderAmount  ProductID Quantity
0      101           1    Yorkshire 2023-07-01       150.0     1001.0      1.0
2      103           1    Yorkshire 2023-07-01       200.5     1001.0      NaN
3      104           3       London 2023-07-05       350.0     1000.0      4.0
4      105           2  Tyne & Wear 2023-07-03       100.0     1003.0      1.0
5      106           1    Yorkshire 2023-07-01       150.0     1001.0      1.0
6      107           2  Tyne & Wear 2023-07-03       100.0     1003.0      1.0
7      108           1    Yorkshire 2023-07-01        50.0     1006.0    Three
8      109           3       London 2023-07-05       970.0     1000.0      3.0

In [47]:
# Fix Quantity.
df['Quantity'].replace('Three', 3.0, inplace=True)
df = df.dropna(subset=['Quantity'])
df.head(10)

/tmp/ipython-input-47-105895401.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].replace('Three', 3.0, inplace=True)
/tmp/ipython-input-47-105895401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quantity'].replace('Three', 3.0, inplace=True)

   OrderID  CustomerID  OrderRegion  OrderDate OrderAmount  ProductID Quantity
0      101           1    Yorkshire 2023-07-01       150.0     1001.0      1.0
3      104           3       London 2023-07-05       350.0     1000.0      4.0
4      105           2  Tyne & Wear 2023-07-03       100.0     1003.0      1.0
5      106           1    Yorkshire 2023-07-01       150.0     1001.0      1.0
6      107           2  Tyne & Wear 2023-07-03       100.0     1003.0      1.0
7      108           1    Yorkshire 2023-07-01        50.0     1006.0      3.0
8      109           3       London 2023-07-05       970.0     1000.0      3.0

In [51]:
# Fix data types.

df['Quantity'] = df['Quantity'].fillna(0).astype(float).astype(int)
df['ProductID'] = df['ProductID'].fillna(0).astype(float).astype(int).astype(str)
df['OrderAmount'] = df['OrderAmount'].fillna(0).astype(float)
df = df.astype({
    'OrderID': str,
    'CustomerID': str,
    'OrderRegion': str
})
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df.head(10)

  OrderID CustomerID  OrderRegion  OrderDate  OrderAmount ProductID  Quantity
0     101          1    Yorkshire 2023-07-01        150.0      1001         1
3     104          3       London 2023-07-05        350.0      1000         4
4     105          2  Tyne & Wear 2023-07-03        100.0      1003         1
5     106          1    Yorkshire 2023-07-01        150.0      1001         1
6     107          2  Tyne & Wear 2023-07-03        100.0      1003         1
7     108          1    Yorkshire 2023-07-01         50.0      1006         3
8     109          3       London 2023-07-05        970.0      1000         3

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      7 non-null      object
 1   CustomerID   7 non-null      object
 2   OrderRegion  7 non-null      object
 3   OrderDate    7 non-null      datetime64[ns]
 4   OrderAmount  7 non-null      float64
 5   ProductID    7 non-null      object
 6   Quantity     7 non-null      int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 448.0+ bytes

In [53]:
# Compute TotalOrderValue.
df['TotalOrderValue'] = df['OrderAmount'] * df['Quantity']
df.head(10)

,OrderID,CustomerID,OrderRegion,OrderDate,OrderAmount,ProductID,Quantity,TotalOrderValue
0,101,1,Yorkshire,2023-07-01,150.0,1001,1,150.0
3,104,3,London,2023-07-05,350.0,1000,4,1400.0
4,105,2,Tyne & Wear,2023-07-03,100.0,1003,1,100.0
5,106,1,Yorkshire,2023-07-01,150.0,1001,1,150.0
6,107,2,Tyne & Wear,2023-07-03,100.0,1003,1,100.0
7,108,1,Yorkshire,2023-07-01,50.0,1006,3,150.0
8,109,3,London,2023-07-05,970.0,1000,3,2910.0

In [54]:
# Save the cleaned file to csv.
df.to_csv('cleaned_orders.csv', index=False)